### ISSUE TITLE
Publish new version to crates.io

### ISSUE THREAD

**Issue by dignifiedquire** [zcash-hackworks/sapling-crypto#100]
The version here is pretty outdated https://crates.io/crates/sapling-crypto, it would be great to have a new version published so we could depend on that instead of the git repo here. 

Background: Trying to publish https://github.com/filecoin-project/rust-proofs to crates and are currently blocked on this dependency for doing so. 

Thank you

**Comment by ebfull** [comment]
We currently depend on a forked version of the `blake2b` crate which exists only in a git repository, so we can't push to `crates.io`. So either

1. they accept https://github.com/cesarb/blake2-rfc/pull/9
2. we fork it and publish a new crate
3. we bring their crate into our tree

**Comment by str4d** [comment]
4. We switch to another BLAKE2 implementation that has personalization support (e.g. the `hashes` crate once https://github.com/RustCrypto/hashes/issues/75 is closed).

**Comment by str4d** [comment]
Update: this will no longer happen, because we have successfully refactored this crate out of existence in zcash/librustzcash#104. Users of this crate should migrate to the next versions of `bellman`, `zcash_primitives`, and `zcash_proofs` when they are published (which should be soon - follow [this milestone](https://github.com/zcash/librustzcash/milestone/1) for progress).

**Comment by str4d** [comment]
As an additional note, the Jubjub and Pedersen hash circuit code was temporarily moved into `zcash_proofs` (and the non-circuit code into `zcash_primitives`) because it requires additional refactoring. It will eventually move either into `bellman` or a companion crate.
